# Generated by Django 3.2.5 on 2021-10-11 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name=4)),
                ('projector', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('date_now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_in', models.DateTimeField()),
                ('booking_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.room')),
            ],
        ),
    ]
